# frozen_string_literal: true

class SearchFieldService
  include Singleton

  SEARCH_FIELDS = [
    'alternative_title_tesim',
    'architect_tesim',
    'archival_collection_box_ssi',
    'archival_collection_folder_ssi',
    'archival_collection_number_ssi',
    'archival_collection_tesi',
    'archival_collection_title_ssi',
    'ark_ssi',
    'arranger_tesim',
    'artist_tesim',
    'author_tesim',
    'binding_note_tesim',
    'caption_tesim',
    'citation_source_tesim',
    'collation_tesim',
    'collector_tesim',
    'colophon_tesim',
    'composer_tesim',
    'condition_note_ssi',
    'contents_note_tesim',
    'contributor_tesim',
    'creator_tesim',
    'date_created_tesim',
    'delivery_tesim',
    'description_tesim',
    'descriptive_title_tesim',
    'explicit_tesim',
    'features_tesim',
    'foliation_tesim',
    'format_book_tesim',
    'genre_tesim',
    'hand_note_tesim',
    'host_tesim',
    'human_readable_language_tesim',
    'identifier_tesim',
    'illuminator_tesim',
    'illustrations_note_tesim',
    'incipit_tesim',
    'inscription_tesim',
    'inscription_tesim',
    'librettist_tesim',
    'local_identifier_ssim',
    'location_tesim',
    'lyricist_tesim',
    'medium_tesim',
    'musician_tesim',
    'named_subject_tesim',
    'opac_url_ssi',
    'other_versions_tesim',
    'page_layout_ssim',
    'page_layout_ssim',
    'photographer_tesim',
    'place_of_origin_tesim',
    'printer_tesim',
    'producer_tesim',
    'program_tesim',
    'provenance_tesim',
    'publisher_tesim',
    'repository_tesim',
    'researcher_tesim',
    'resp_statement_tesim',
    'scribe_tesim',
    'script_tesim',
    'script_tesim',
    'series_tesim',
    'shelfmark_ssi',
    'subject_geographic_tesim',
    'subject_temporal_tesim',
    'subject_tesim',
    'subject_topic_tesim',
    'summary_tesim',
    'support_tesim',
    'title_tesim',
    'toc_tesim',
    'uniform_title_tesim',
    'uniform_title_tesim',
    'writing_system_tesim',
  ].join(' ').freeze

  def search_fields
    SEARCH_FIELDS
  end
end
