inherit_gem:
  bixby: bixby_default.yml

AllCops:
  TargetRubyVersion: 2.4


Layout/MultilineBlockLayout:
  Exclude:
    - spec/features/search_catalog_spec.rb

Layout/BlockEndNewline:
  Exclude:
    - spec/features/search_catalog_spec.rb

Lint/RequireParentheses:
  Exclude:
    - app/helpers/blacklight_helper.rb

Layout/SpaceInsidePercentLiteralDelimiters:
  Exclude:
    - spec/services/search_field_service_spec.rb

Metrics/AbcSize:
  Exclude:
    - app/helpers/blacklight/url_helper_behavior.rb
    - app/controllers/catalog_controller.rb

Metrics/BlockLength:
  Enabled: true
  Exclude:
    - '**/*/catalog_controller.rb'
    - 'config/**/*'
    - 'spec/**/*'
    - lib/tasks/ingest.rake
    - lib/tasks/derivatives.rake
    - app/models/ucla_metadata.rb

Metrics/ClassLength:
  Enabled: true
  Exclude:
    - app/controllers/catalog_controller.rb
    - app/importers/californica_mapper.rb

Metrics/CyclomaticComplexity:
  Exclude:
    - app/helpers/blacklight/url_helper_behavior.rb
    - app/helpers/blacklight/blacklight_helper_behavior.rb

Metrics/LineLength:
  Exclude:
    - spec/tasks/ingest_spec.rb
    - spec/services/search_field_service_spec.rb
    - app/importers/rights_statement_validator.rb
    - spec/features/import_and_show_work_spec.rb
    - app/importers/actor_record_importer.rb
    - app/controllers/catalog_controller.rb
    - app/helpers/blacklight_helper.rb


Metrics/MethodLength:
  Enabled: true
  Exclude:
    - app/importers/californica_csv_parser.rb
    - app/importers/actor_record_importer.rb
    - app/forms/hyrax/californica_collections_form.rb
    - app/helpers/blacklight/url_helper_behavior.rb
    - app/controllers/catalog_controller.rb

Metrics/PerceivedComplexity:
  Exclude:
    - app/helpers/blacklight/url_helper_behavior.rb
    - app/helpers/blacklight/blacklight_helper_behavior.rb

Performance/RegexpMatch:
  Exclude:
    - app/helpers/blacklight/url_helper_behavior.rb

Rails/FilePath:
  Enabled: false

RSpec/DescribeClass:
  Exclude:
    - 'spec/tasks/**/*'
    - 'spec/views/**/*'
    - 'spec/features/**/*'

RSpec/ExampleLength:
  Enabled: true
  Max: 50
  Exclude:
    - 'spec/features**/*'
    - spec/tasks/ingest_spec.rb
    - spec/importers/californica_mapper_spec.rb
    - 'spec/helpers**/*'

RSpec/NotToNot:
  Enabled: false

RSpec/LetSetup:
  Exclude:
    - spec/features/search_catalog_spec.rb

RSpec/AnyInstance:
  Enabled: false

Rails/OutputSafety:
  Exclude:
    - app/helpers/blacklight/url_helper_behavior.rb
    - app/helpers/blacklight_helper.rb
    - app/processors/custom_join.rb

Style/BlockComments:
  Exclude:
    - app/presenters/ursus/collection_block_presenter.rb
    - spec/presenters/ursus/collection_block_presenter_spec.rb  

Style/BlockDelimiters:
  Exclude:
    - spec/features/search_catalog_spec.rb

Style/IfUnlessModifier:
  Exclude:
    - app/helpers/blacklight/url_helper_behavior.rb
    - app/helpers/blacklight_helper.rb
    - app/controllers/catalog_controller.rb

Style/AndOr:
  Exclude:
  - app/helpers/blacklight_helper.rb

Style/MethodDefParentheses:
  Exclude:
    - app/helpers/blacklight/url_helper_behavior.rb
    - app/helpers/blacklight/blacklight_helper_behavior.rb

Style/GuardClause:
  Exclude:
    - app/controllers/catalog_controller.rb
    - app/helpers/blacklight_helper.rb

Style/IfInsideElse:
  Exclude:
     - app/controllers/application_controller.rb
     - app/services/iiif_service.rb

Lint/UselessAssignment:
  Exclude:
     - app/controllers/application_controller.rb


Metrics/ModuleLength:
  Exclude:
     - app/helpers/blacklight/blacklight_helper_behavior.rb

Style/MethodDefParentheses:
  Exclude:
    - app/helpers/blacklight/blacklight_helper_behavior.rb
