require 'simplecov'
require 'coveralls'

# Ignore files automatically generated by Rails

SimpleCov.formatter = Coveralls::SimpleCov::Formatter
SimpleCov.start do
   add_filter 'channel.rb'
   add_filter 'connection.rb'
   add_filter 'application_job'
   add_filter 'application_mailer'
end
