sudo: true
language: minimal
services:
  - docker
env:
  global:
    - DOCKER_COMPOSE_VERSION=1.23.2
    - secure: "N7Xkgo7xtlzPeZoGMC8cQ+EL6dB6GjKhhx9dTcnAMu3zdod/5Eqbgmxn+FuYu7AuqBN9cPhFsAiDwjxPSla5CTKndtbNVnNOTsnNjpznC5xYLclRY4XdPlwNVzsfX43bSqlBGQnNO8GmjwyMycETxlkHNAZzhkbVaY5GTdolAKwyl4ak4wAxMDI1iyAY0So3YpkS9ZOVYXdnnS3SqatP4aJOMzs28Idfa7LUKVoRWGTU2x5v+LUj+R4uPykV0A7CPQ/c12TWOfktIY+N/y7vWcGzxT2xLzAD4wUZFI8ST4NiF6/aUg4bJCsMicz6Mzvs00TN5KQaLSHg1mte7H5J9NM+RIyAgH6GJFj80e8Q/Sh3zYZeoF5uA/5NDdGrd0hYksMISjXiz2Haa0Z1+/MwAzOnpP98hX7XRb36MR3W6l1R4PQ695T7ZTOGl08um1DpvHDPt5NQbrwUZVjLcVELRIlRENvawDQ76Y2icH0dKPeTAA34R7CCPGhl5XCHcrA3fgFzpNhLUMxsJdJgGRNDQXqwF+xO7uVr9Q8PxPOfxprv31WuTHn189FlCI63XYlh1BcTj3jXQsM9/cqUzQ1BwFPsJA9rogmOeIiDGHdM6Aq7xRUqaoe/7ZX1WM9JVletipLjFSJRniIdhJ/AvwUNBiybk+N6bl/oor/tTSLpy/Y="
    - secure: "AkeBX5IfGGlj9koT0Xr14kn3b1AgnNYJEXf/cwcVmwTPxEvcCa0f8Tcl6ToHxRg6RUUQP/znq4QUa3P0e91qBeZQpo6Kf8yGQXXXtt4R/hFDwcxQsfaNEeASnTxed83clPrelS4Q2N/XVpnYz2b+fDwh6lHvjn+KQue55r1MWQpqIoXCxO4x4WVP5f2umByWbV0iEWAt0zfPONLXNwGn/eMZXz3xVEUGG+6mxc1eWyIvUiPjxEPd5GVnyyIf9T4II7UgvF8Rx88stWTimvzcZK5TVdeNamjrjYrnCznNLGEISiN4Zbb1UQUHaKeLQc0VMdHdFLH3L5qdZ5DvVH2VH9ledXPjrfdYMYnWbrB+hVlJtYuSqs75Deu3qtoE6swaaq65q3dy/+YfwxTNIj3pr/HJOilwZtvN1GNj+5QtvhbTSbneBtZVBl9D/el8C5l209cHx69nsCYoCg1Wb35YlQSYBYuUv2ABRx6ixLB+7ZnewHSWFZPf9j1Ssw4PBw9kKhHLYMzyoyrnfiNJ26agpt3B5Q6uhSQ+QAKDKl6NZdhmsWBgXsxbte3h8pNlHjGtZqNYzSeIf0g4OTZVEcR38IPg/J3M9p0P+K+vQPQZ2JiMFlQ2eYmHwQj/8c6Hus8TEcq7LYDyFmVm+E55wofpdSNbUE2cLeCfvFxDPAI3hCg="
addons:
  apt:
    packages:
    - chromium-browser
    - chromium-chromedriver
before_install:
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin
script:
  - docker-compose up -d
  - docker-compose run web gem install bundler
  - docker-compose run web bundle install
  - docker-compose run web yarn install
  - docker-compose run web bundle exec rubocop
  - docker-compose run web bundle exec rake db:setup
  - docker-compose run web yarn run pa11y-ci --threshold 10
  - docker-compose run web bundle exec rspec
notifications:
  email: false
after_success:
- |
  if [[ $TRAVIS_BRANCH == 'master' && $TRAVIS_PULL_REQUEST == 'false' ]]; then
    curl "$JENKINS_DEPLOY_URL"
  fi
  if [[ $TRAVIS_TAG != "" ]]; then
    curl "$JENKINS_TAG_DEPLOY_URL"
  fi
