version: "3.6"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - db
      - solr
    env_file:
      - ./default.env
      - ./docker.env
    environment:
      SOLR_URL: http://solr:8983/solr/ursus
      SOLR_TEST_URL: http://solr_test:8983/solr/ursus
      DATABASE_USERNAME: ursus
      DATABASE_PASSWORD: ursus
      RAILS_HOST: web
    expose:
      - 3000
    volumes:
    - .:/ursus
  
  sinai:
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: 'sh start-sinai.sh'
    depends_on:
      - db
      - solr
    env_file:
      - ./default.env
      - ./docker.env
    environment:
      DATABASE_NAME: sinai
      DATABASE_USERNAME: ursus
      DATABASE_PASSWORD: ursus
      SOLR_URL: http://solr:8983/solr/sinai
      SOLR_TEST_URL: http://solr_test:8983/solr/sinai
      RAILS_HOST: sinai
    expose:
      - 3000
    volumes:
    - .:/ursus

  db:
    image: mysql:5.6
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "127.0.0.1:3306:3306"
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  solr:
    image: uclalibrary/solr-ursus

  solr_test:
    image: uclalibrary/solr-ursus
