FROM uclalibrary/ursus

WORKDIR /ursus

RUN apt-get update -qq
# New apt packages - these can be removed once they're incorporated into the base uclalibrary/ursus image on dockerhub
RUN apt-get install -y nodejs

EXPOSE 3000

# Install Ruby Gems
COPY Gemfile /ursus/Gemfile
COPY Gemfile.lock /ursus/Gemfile.lock
RUN bundle install

# Install node packages
COPY package.json /ursus/package.json
COPY yarn.lock /ursus/yarn.lock
RUN yarn install --frozen-lockfile

# Add ursus
COPY / /ursus
