version: "3.6"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - db
      - solr
    env_file:
      - ./default.env
      - ./docker.env
    environment:
      SOLR_URL: http://solr:8983/solr/ursus
      SOLR_TEST_URL: http://solr_test:8983/solr/ursus
      DATABASE_USERNAME: ursus
      DATABASE_PASSWORD: ursus
      RAILS_HOST: web
    expose:
      - 3000
  
  sinai:
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: 'sh start-sinai.sh'
    depends_on:
      - db
      - solr
    env_file:
      - ./default.env
      - ./docker.env
    environment:
      DATABASE_NAME: sinai
      DATABASE_USERNAME: ursus
      DATABASE_PASSWORD: ursus
      SOLR_URL: http://solr:8983/solr/sinai
      SOLR_TEST_URL: http://solr_test:8983/solr/sinai
      RAILS_HOST: sinai
    expose:
      - 3000

  db:
    image: mysql:5.6
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  
  e2e:
    build: ./e2e
    env_file:
      - ./default.env
      - ./docker.env
    environment:
      - CI
      - CONTINUOUS_INTEGRATION
      - DEBIAN_FRONTEND
      - HAS_JOSH_K_SEAL_OF_APPROVAL
      - PERCY_TOKEN
      - TRAVIS
      - TRAVIS_ALLOW_FAILURE
      - TRAVIS_APP_HOST
      - TRAVIS_BRANCH
      - TRAVIS_BUILD_DIR
      - TRAVIS_BUILD_ID
      - TRAVIS_BUILD_NUMBER
      - TRAVIS_BUILD_STAGE_NAME
      - TRAVIS_BUILD_WEB_URL
      - TRAVIS_COMMIT
      - TRAVIS_COMMIT_MESSAGE
      - TRAVIS_COMMIT_RANGE
      - TRAVIS_COMPILER
      - TRAVIS_CPU_ARCH
      - TRAVIS_DEBUG_MODE
      - TRAVIS_DIST
      - TRAVIS_EVENT_TYPE
      - TRAVIS_JOB_ID
      - TRAVIS_JOB_NAME
      - TRAVIS_JOB_NUMBER
      - TRAVIS_JOB_WEB_URL
      - TRAVIS_OS_NAME
      - TRAVIS_OSX_IMAGE
      - TRAVIS_PULL_REQUEST
      - TRAVIS_PULL_REQUEST_BRANCH
      - TRAVIS_PULL_REQUEST_SHA
      - TRAVIS_PULL_REQUEST_SLUG
      - TRAVIS_REPO_SLUG
      - TRAVIS_SECURE_ENV_VARS
      - TRAVIS_SUDO
      - TRAVIS_TAG
      - TRAVIS_TEST_RESULT

  solr:
    image: uclalibrary/solr-ursus:2020-07-22

  solr_test:
    image: uclalibrary/solr-ursus:2020-07-22
