version: "3.6"

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile.ci
    depends_on:
      - db
      - solr
    env_file:
      - ./default.env
      - ./docker.env
    environment:
      SOLR_URL: http://solr:8983/solr/ursus
      SOLR_TEST_URL: http://solr_test:8983/solr/ursus
      DATABASE_USERNAME: ursus
      DATABASE_PASSWORD: ursus
      RAILS_HOST: web
    expose:
      - 3000
  
  sinai:
    build:
      context: .
      dockerfile: Dockerfile.ci
    command: 'sh start-sinai.sh'
    depends_on:
      - db
      - solr
    env_file:
      - ./default.env
      - ./docker.env
    environment:
      DATABASE_NAME: sinai
      DATABASE_USERNAME: ursus
      DATABASE_PASSWORD: ursus
      SOLR_URL: http://solr:8983/solr/sinai
      SOLR_TEST_URL: http://solr_test:8983/solr/sinai
      RAILS_HOST: sinai
    expose:
      - 3000

  db:
    image: mysql:5.6
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
  
  e2e:
    build: ./e2e
    env_file:
      - ./default.env
      - ./docker.env
    environment:
      PERCY_BRANCH: $TRAVIS_PULL_REQUEST_BRANCH
      PERCY_COMMIT: $TRAVIS_COMMIT
      PERCY_PULL_REQUEST: $TRAVIS_PULL_REQUEST
      PERCY_TOKEN: $PERCY_TOKEN
      TRAVIS_BRANCH: $TRAVIS_BRANCH
      TRAVIS_PULL_REQUEST: $TRAVIS_PULL_REQUEST

  solr:
    image: uclalibrary/solr-ursus

  solr_test:
    image: uclalibrary/solr-ursus
