version: '2.0'

services:
  web:
    build: .
    hostname: ursus
    depends_on:
      - db
      - solr
    env_file:
      - ./default.env
      - ./docker.env
    healthcheck:
      test: ["CMD", "curl", "--fail", "http://localhost:3000", "||", "exit", "1"]
    ports:
      - '127.0.0.1:3003:3000'
    volumes:
      - .:/ursus
      - ursus_public_uv:/ursus/public/uv
      - ursus_tmp:/ursus/tmp
    working_dir: /ursus

  db:
    image: mysql:5.6
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - mysql_data:/var/lib/mysql
    ports:
      - '127.0.0.1:3306:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  solr:
    image: uclalibrary/solr-ursus:2021-03-01
    ports:
      - '127.0.0.1:8983:8983'

  solr_test:
    image: uclalibrary/solr-ursus:2021-03-01
    ports:
      - '127.0.0.1:8985:8983'

volumes:
  mysql_data:
  ursus_bundle_dir:
  ursus_node_modules:
  ursus_public_uv:
  ursus_tmp:
