# These fields are in order of display

# Sinai only - Codicology
extent_tesim: 'Extent'
collation_tesim: 'Collation'
form_sim: 'Form'
support_tesim: 'Support'
writing_system_tesim: 'Writing system'
script_tesim: 'Script'
page_layout_ssim: 'Page layout'
foliation_tesim: 'Foliation note'
hand_note_tesim: 'Hand note'
script_tesim: 'Script note'
binding_note_tesim: 'Binding note'
condition_note_tesim: 'Condition note'
description_tesim: 'Physical Description note'
