# These fields are in order of display

# Sinai only - Codicology
extent_tesim: 'Extent'
collation_tesim: 'Collation'
form_sim: 'Form'
support_sim: 'Support'
writing_system_tesim: 'Writing system'
script_tesim: 'Script'
#ink_color_sim: 'Ink color'
page_layout_ssim: 'Page layout'
foliation_tesim: 'Foliation note'
hand_note_tesim: 'Hand note' #???
script_sim: 'Script note' #???
binding_note_ssi: 'Binding note'
condition_note_ssi: 'Condition note'
description_tesim: 'Description note' #???
