# These fields are in order of display

# Sinai only - Overview
place_of_origin_tesim: 'Place of origin'
date_created_tesim: 'Date created'
foliation_tesim: 'Foliation'
form_ssi: 'Form'
human_readable_language_tesim: 'Language'
writing_system_tesim: 'Writing system'
script_tesim: 'Script'
repository_tesim: 'Repository'
human_readable_rights_statement_tesim: 'Rights statement'
services_contact_ssm: 'Rights contact'
