human_readable_rights_statement_tesim: 'Rights statement'
local_rights_statement_ssm: 'Local Rights statement'
services_contact_ssm: 'Rights Contact'
rights_holder_tesim: 'Rights Holder'
rights_country_tesim: 'Rights (country of creation)'
funding_note_tesim: 'Funding Note'
