content_disclaimer_ssm: 'Content Disclaimer'
alternative_title_tesim: 'Alternative Title'
photographer_tesim: 'Photographer'
date_created_tesim: 'Date Created'
program_tesim: 'Program'
extent_tesim: 'Extent'
