repository_tesim: 'Repository'
local_identifier_ssm: 'Local identifier'
finding_aid_url_ssm: 'Finding aid url'
opac_url_tesim: 'Opac url'
oclc_ssi: 'OCLC Number'
ark_ssi: 'ARK'
other_versions_tesim: 'Other version(s)'
