# These fields are in order of display

# Titles
title_tesim: 'Title'
alternative_title_tesim: 'Alternative Title'
uniform_title_tesim: 'Uniform title'

# Relators
creator_tesim: 'Creator'
author_tesim: 'Author'
architect_tesim: 'Architect'
photographer_tesim: 'Photographer'
composer_tesim: 'Composer'
commentator_tesim: 'Commentator'
scribe_tesim: 'Scribe'
illuminator_tesim: 'Illuminator'
rubricator_tesim: 'Rubricator'
lyricist_tesim: 'Lyricist'
illustrator_tesim: 'Illustrator'
calligrapher_tesim: 'Calligrapher'
editor_tesim: 'Editor'
engraver_tesim: 'Engraver'
printmaker_tesim: 'Printmaker'
translator_tesim: 'Translator'

# Publication info
publisher_tesim: 'Publisher'
place_of_origin_tesim: 'Place of Origin'
year_isim: 'Year'
normalized_date_sim: 'Date'
date_created_tesim: 'Date Created'

# Other
human_readable_language_tesim: 'Language'
member_of_collections_ssim: 'Collection'
# dlcs_collection_name_tesim: 'Collection (native)'
