content_disclaimer_ssm: 'Content Disclaimer'

# Titles
title_tesim: 'Title'
alternative_title_tesim: 'Alternative Title'
uniform_title_tesim: 'Uniform title'

# Relators
creator_tesim: 'Creator'
author_tesim: 'Author'
editor_tesim: 'Editor'
photographer_tesim: 'Photographer'
architect_tesim: 'Architect'
illuminator_tesim: 'Illuminator'
illustrator_tesim: 'Illustrator'
engraver_tesim: 'Engraver'
printmaker_tesim: 'Printmaker'
scribe_tesim: 'Scribe'
translator_tesim: 'Translator'
rubricator_tesim: 'Rubricator'
calligrapher_tesim: 'Calligrapher'
commentator_tesim: 'Commentator'
lyricist_tesim: 'Lyricist'
composer_tesim: 'Composer'
musician_tesim: 'Musician'
researcher_tesim: 'Researcher'
printer_tesim: 'Printer'
host_tesim: 'Host'
interviewer_tesim: 'Interviewer'
interviewee_tesim: 'Interviewee'
cartographer_tesim: 'Cartographer'
artist_tesim: 'Artist'
recipient_tesim: 'Recipient'
director_tesim: 'Director'
producer_tesim: 'Producer'
arranger_tesim: 'Arranger'
collector_tesim: 'Collector'
librettist_tesim: 'Librettist'

# Publication info
date_created_tesim: 'Date Created'
normalized_date_sim: 'Date'
year_isim: 'Year'
place_of_origin_tesim: 'Place of Origin'
publisher_tesim: 'Publisher'
edition_ssm: 'Edition'

# Other
human_readable_language_tesim: 'Language'
script_tesim: 'Script'
member_of_collections_ssim: 'Collection'
series_tesim: 'Series'
# dlcs_collection_name_tesim: 'Collection (native)'

associated_name_tesim: 'Associated name'
descriptive_title_tesim: 'Descriptive title'
references_tesim: 'References'
shelfmark_ssi: 'Shelfmark'
program_tesim: 'Program'
