caption_tesim: 'Caption'
summary_tesim: 'Summary'
description_tesim: 'Description'
provenance_tesim: 'Provenance'
colophon_tesim: 'Colophon'
toc_tesim: 'Table of Contents'
contents_note_tesim: 'Contents note'
incipit_tesim: 'Incipit'
explicit_tesim: 'Explicit'
