summary_tesim: 'Summary'
description_tesim: 'Description'
caption_tesim: 'Caption'
inscription_tesim: 'Inscription'
contents_note_tesim: 'Contents note'
colophon_tesim: 'Colophon'
history_tesim: 'History'
provenance_tesim: 'Provenance'
note_tesim: 'Note'
related_to_ssm: 'Related items'
human_readable_related_record_title_ssm: 'Related records'
# toc_tesim: 'Table of Contents' (render_table_of_contents_key / value)
resp_statement_tesim: 'Statement of Responsibility'
citation_source_tesim: 'References'

incipit_tesim: 'Incipit'
explicit_tesim: 'Explicit'
