extent_tesim: 'Extent'
dimensions_tesim: 'Dimensions'
format_tesim: 'Format'
format_book: 'Format'
support_tesim: 'Support'
medium_tesim: 'Medium'
page_layout_ssim: 'Page layout'
binding_note_ssi: 'Binding note'
condition_note_ssi: 'Condition note'
collation_tesim: 'Collation'
foliation_tesim: 'Foliation'
illustrations_note_tesim: 'Illustrations note'
form_ssi: 'Form'
