extent_tesim: 'Extent'
dimensions_tesim: 'Dimensions'
collation_tesim: 'Collation'
foliation_tesim: 'Foliation'
format_tesim: 'Format'
medium_tesim: 'Medium'
support_tesim: 'Support'
page_layout_ssim: 'Page layout'
writing_system_tesim: 'Writing system'
script_tesim: 'Script'
writing_and_hands_tesim: 'Writing and hands'
illustrations_note_tesim: 'Illustrations note'
condition_note_ssi: 'Condition note'
binding_note_ssi: 'Binding note'
inscription_tesim: 'Inscription'
opac_url_tesim: 'Opac url'
