title_tesim: 'Title'
description_tesim: 'Description'
creator_tesim: 'Creator'
contributor_tesim: 'Contributor'
photographer_tesim: 'Photographer'
caption_tesim: 'Caption'
services_contact_ssm: 'Rights services contact'
