repository_tesim: 'Repository'
local_identifier_ssm: 'Local identifier'
# OCLC Number
ark_ssi: 'ARK'
# Rights statement
rights_country_tesim: 'Rights (country of creation)'
rights_holder_tesim: 'Rights Holder'
services_contact_ssm: 'Rights contact'
license_tesim: 'License'
funding_note_ssm: 'Funding Note'
# Depositor
date_uploaded_tesim: 'Date Uploaded'
date_modified_tesim: 'Date Modified'
# Filename
# Import URL
# Source
