name: Run CI Suite

on:
  pull_request:
    branches: [ master ]

env:
  COMPOSE_FILE: docker-compose-standalone.yml

jobs:

  rubocop:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Set up Ruby
      uses: ruby/setup-ruby@b818bea8cf015031920150a891dbdd4105cc7e47
      with:
        ruby-version: '2.5'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: erblint
      run: bundle exec erblint --lint-all

  erblint:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Set up Ruby
      uses: ruby/setup-ruby@b818bea8cf015031920150a891dbdd4105cc7e47
      with:
        ruby-version: '2.5'
        bundler-cache: true # runs 'bundle install' and caches installed gems automatically
    - name: erblint
      run: bundle exec erblint --lint-all

  rspec:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Start docker services
      run: docker-compose up --detach db solr_test
    - name: Initialize DB
      run: docker-compose run web bundle exec rails db:setup
    - name: run rspec
      run: docker-compose run web bundle exec rspec spec
    - name: Stop docker services
      run: docker-compose down
  
  cypress:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@5a4ac9002d0be2fb38bd78e4b4dbde5606d7042f
    - name: Login to DockerHub
      uses: docker/login-action@f3364599c6aa293cdc2b8391b1b56d0c30e45c8a
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - name: Start docker services
      run: docker-compose up --detach
    - name: Initialize DBs
      run: |
        docker-compose up --detach db
        docker-compose run web bundle exec rails db:setup
        docker-compose run sinai bundle exec rails db:setup
    - name: restart sinai container (can only set feature flag after db init)
      run: docker-compose restart sinai
    - name: prime the OAI-PMH rails engine (first load can be very slow)
      run: curl localhost:3003/catalog/oai?verb=Identify
    - uses: cypress-io/github-action@224f894ce0b082eba28a3a4562f630c54a17b432
      with:
        command-prefix: 'percy exec -- npx'
        working-directory: e2e
      env: 
        PERCY_TOKEN: ${{ secrets.PERCY_TOKEN }}
    - name: Stop docker services
      run: docker-compose down
