name: On merge

on:
    push:
        branches: 
            - main

jobs:
    deploy-ursus:
        name: Deploy Ursus main branch to test
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v1
        - name: Jenkins webhook
          uses: enflo/curl-action@fabe347922c7a9e88bafa15c4b7d6326ea802695
          with:
            curl: 'https://${{ secrets.JENKINS_USER }}@${{ secrets.JENKINS_HOST }}/job/DeployUrsus/buildWithParameters?GIT_BRANCH=main&cause=GitHub+Action+Post+Merge+Build&DEPLOY_HOST=t-w-ursus01.library.ucla.edu&token=${{ secrets.JENKINS_API_URSUS_TOKEN }}'

